version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: fuksilaiterekisteri_dev
    environment:
      - STUDENT_API_URL=http://sis-importer-db-api:3000
      - SIS=true
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - EMAIL_ENABLED=false
      - SUPERADMINS=
      - E2E=$E2E
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    container_name: fuksilaiterekisteri_dev
  adminer_fular:
    container_name: adminer_fukrek
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=db
    image: adminer:4.7.5
    ports:
      - 8080:8080 # localhost:8080/?pgsql=db&username=postgres&db=postgres&ns=public
  db:
    image: postgres:11
    container_name: fuksilaiterekisteri_db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data_test:/data

volumes:
  pg_data_test: