version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: fuksilaiterekisteri_dev
    environment:
      - STUDENT_API_URL=https://oodikone.cs.helsinki.fi/fukrek/mock
      - SIS=false
      - STUDENT_API_TOKEN=test
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - EMAIL_ENABLED=false
      - SUPERADMINS=
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    container_name: fuksilaiterekisteri_dev
  db:
    image: postgres:11
    container_name: fuksilaiterekisteri_db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data

volumes:
  pg_data:
