version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: fuksilaiterekisteri_dev
    environment:
      - STUDENT_API_URL=https://api-toska.apps.ocp-prod-0.k8s.it.helsinki.fi/importer
      - SIS=true
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - EMAIL_ENABLED=false
      - SUPERADMINS=
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    container_name: fuksilaiterekisteri_dev
  db:
    image: postgres:11
    container_name: fuksilaiterekisteri_db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
  adminer:
    container_name: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=db
    image: adminer:4.7.5
    ports:
      - 8080:8080 # localhost:8080/?pgsql=db&username=postgres&db=postgres&ns=public

volumes:
  pg_data:
