version: 2
jobs:
  build:
    machine:
      # specify the version you desire here
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout

      - run: docker build . -t toska/fuksilaiterekisteri:production --build-arg BASE_PATH=/fuksilaite/

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker push toska/fuksilaiterekisteri:production