version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
workflows:
  deploy:
    jobs:
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          tag: 'staging'
          extra_build_args: '--build-arg BASE_PATH=/fuksilaite/'
          filters:
            branches:
              only: trunk
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          tag: 'production'
          extra_build_args: '--build-arg BASE_PATH=/fuksilaite/'
          filters:
            branches:
              only: master
