version: 2.1
orbs:
  docker: circleci/docker@0.5.1
jobs:
  cypress:
    image: cypress/base:8
    executor:
      name: docker/docker
      tag: '3.6'
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker
      - run: sudo apt-get update
      - run: sudo apt-get install libgconf-2-4
      - run: docker-compose up -d
      - run: npm ci
      - run: npm install -g wait-on
      - run: wait-on http://localhost:8000
      - run: npm run cypress:run
  lint:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

workflows:
  test-and-deploy:
    jobs:
      - cypress
      - lint
