version: 2.1
orbs:
  docker: circleci/docker@0.5.1
jobs:
  build:
    executor:
      name: docker/docker
      tag: '3.6'
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker
      - run: docker-compose up -d
  install:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm ci
  cypress:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm run cypress:run
  lint:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm run lint

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - install
      - cypress:
          requires:
            - build
            - install
      - lint:
          requires:
            - build
            - install
