version: 2.1
orbs:
  docker: circleci/docker@0.5.1
executors:
  fukrek-executor:
    machine:
      image: ubuntu-1604:201903-01
jobs:
  cypress:
    executor: fukrek-executor
    steps:
      - checkout
      - run: docker-compose up -d
      - run: npm ci
      - run: npm run cypress:run
  lint:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

workflows:
  test-and-deploy:
    jobs:
      - cypress
      - lint
