version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
jobs:
  build:
    docker:
      image: circleci/node:stretch
    steps:
      - checkout
      - run: npm run dev
  cypress:
    docker:
      image: circleci/node:stretch
    steps:
      - checkout
      - run: npm run cypress:run
  lint:
    docker:
      image: circleci/node:stretch
    steps:
      - checkout
      - run: npm run lint

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - cypress:
          requires:
            - build
      - lint:
          requires:
            - build
