version: 2.1
orbs:
  docker: circleci/docker@0.5.1
executors:
  fukrek-executor:
    machine:
      image: ubuntu-1604:201903-01
jobs:
  install-and-test:
    executor: fukrek-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npmcache-v2-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: npmcache-v2-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - run: docker-compose up -d
      - run: timeout 5m bash -c 'until $(curl --output /dev/null --silent --fail http://localhost:8000); do printf .; sleep 5; done'
      - run: npm run db:seed
      - run: npm run lint
      - run: npm run cypress:run

workflows:
  test-and-deploy:
    jobs:
      - install-and-test
