version: 2.1
orbs:
  docker: circleci/docker@0.5.1
jobs:
  cypress:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run: npm ci
      - run: npm install -g wait-on
      - docker/install-docker-tools
      - setup_remote_docker
      - run: docker-compose up -d
      - run: wait-on http://localhost:8000
      - run: npm run cypress:run
  lint:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

workflows:
  build-test-and-deploy:
    jobs:
      - cypress
      - lint
