version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
jobs:
  build:
    steps:
      - checkout
      - run: npm ci
      - run: npm run dev
  test:
    steps:
      - checkout
      - run: npm run lint
      - run: npm run cypress:run
  dockerhub/publish/staging:
    image: toska/$CIRCLE_PROJECT_REPONAME
    tag: 'staging'
    extra_build_args: '--build-arg BASE_PATH=/fuksilaite/'
    filters:
      branches:
        only: trunk
  dockerhub/publish/production:
    image: toska/$CIRCLE_PROJECT_REPONAME
    tag: 'production'
    extra_build_args: '--build-arg BASE_PATH=/fuksilaite/'
    filters:
      branches:
        only: master

workflows:
  build&test&deploy:
    jobs:
      - build
      - test:
          requires:
            - build
