version: 2.1
orbs:
  docker: circleci/docker@0.5.1
executors:
  fukrek-executor:
    machine:
      image: ubuntu-1604:201903-01
jobs:
  install-and-test:
    executor: fukrek-executor
    steps:
      - checkout
      - run: npm ci
      - run: docker-compose up -d
      - run: npm install -g wait-on
      - run: wait-on http://localhost:8000
      - run: npm run cypress:run
      - run: npm run lint

workflows:
  test-and-deploy:
    jobs:
      - install-and-test
