version: 2.1
orbs:
  docker: circleci/docker@0.5.1
executors:
  fukrek-executor:
    machine:
      image: ubuntu-1604:201903-01
jobs:
  install:
    executor: fukrek-executor
    steps: 
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: node_modules
  cypress:
    executor: fukrek-executor
    steps:
      - checkout
      - run: docker-compose up -d
      - run: npm install -g wait-on
      - run: wait-on http://localhost:8000
      - run: npm run cypress:run
  lint:
    executor: fukrek-executor
    steps:
      - checkout
      - run: npm run lint

workflows:
  test-and-deploy:
    jobs:
      - install
      - cypress:
          requires:
            - install
      - lint:
        requires:
            - install
