name: Build production-image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.15
        with:
          name: toska/fuksilaiterekisteri
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: BASE_PATH=/fuksilaite/
          tags: 'production'
          cache: true
