name: Build production-image

on:
  release:
    types: [published]

jobs:
  test:
    name: "Run linter and Cypress tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: Run cypress tests
        run: ./node_modules/.bin/cypress run --headless *.spec.js

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: fuksilaiterekisteri
          tags: production ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            BASE_PATH=/fuksilaite
            GIT_SHA=${{ github.sha }}
            NODE_ENV=production
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: always()
    steps:
      - name: Notify failed
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        if: (needs.test.result != 'success' || needs.build.result != 'success')
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: test-failure
      - name: Notify success
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.4.2
        if: (needs.test.result == 'success' || needs.build.result == 'success')
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment
          deployment-target: production
          softa-url: https://study.cs.helsinki.fi/fuksilaite/
