name: Test and build staging-image

on:
  push:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: npm run db:seed
        run: npm run db:seed

      - name: Run cypress tests
        run: ./node_modules/.bin/cypress run --headless *.spec.js

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/fuksilaiterekisteri/fuksilaiterekisteri/cypress/screenshots/
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: /home/runner/work/fuksilaiterekisteri/fuksilaiterekisteri/cypress/screenshots/

      # - uses: actions/checkout@master
      # - name: Publish to DockerHub
      #   uses: elgohr/Publish-Docker-Github-Action@2.15
      #   with:
      #     name: toska/lomake
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     buildargs: BASE_PATH=/tilannekuva/
      #     tags: 'staging'
      #     cache: true
