name: Test and build staging-image

on:
  push:
    branches: [master]

jobs:
  test:
    name: "Run linter and Cypress tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: Run cypress tests
        run: ./node_modules/.bin/cypress run --headless *.spec.js

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/fuksilaiterekisteri/fuksilaiterekisteri/cypress/screenshots/
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: /home/runner/work/fuksilaiterekisteri/fuksilaiterekisteri/cypress/videos/

  build:
    name: 'Build and publish staging image'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/fuksilaiterekisteri
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: BASE_PATH=/fuksilaite/,NODE_ENV=staging,GITHUB_SHA=${{ github.sha }},SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          tags: staging

  notify:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: always()
    steps:
      - name: Notify failed
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.3.2
        if: (needs.test.result != 'success' || needs.build.result != 'success')
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: test-failure
      - name: Notify success
        uses:  UniversityOfHelsinkiCS/slackbot-action@v1.3.2
        if: (needs.test.result == 'success' || needs.build.result == 'success')
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          message-type: deployment
          deployment-target: staging
          softa-url: https://toska-staging.cs.helsinki.fi/fuksilaite/
