name: Test and build staging-image

on:
  push:
    branches: [master]

jobs:
  sentry:
    name: "Make sentry release and upload sourcemaps"
    runs-on: ubuntu-16.04
    env:
      SENTRY_PROJECT: fuksilaiterekisteri
      SENTRY_ORG: sentry
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build
      
      - name: Make Sentry release
        run: npm run sentry-cli -- releases new --finalize fuksilaiterekisteri@$GITHUB_SHA

      - name: Upload sourcemaps
        run: npm run sentry-cli -- releases files fuksilaiterekisteri@$GITHUB_SHA upload-sourcemaps --url-prefix ~/fuksilaite/ --rewrite dist

  test:
    name: "Run linter and Cypress tests"
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: npm run db:seed
        run: npm run db:seed

      - name: Run cypress tests
        run: ./node_modules/.bin/cypress run --headless *.spec.js

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/fuksilaiterekisteri/fuksilaiterekisteri/cypress/screenshots/
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: /home/runner/work/fuksilaiterekisteri/fuksilaiterekisteri/cypress/videos/

  build:
    name: 'Build and publish staging image'
    needs: [test,sentry]
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/fuksilaiterekisteri
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: BASE_PATH=/fuksilaite/,SENTRY_IDENTIFIER=staging,GITHUB_SHA=${{ github.sha }}
          tags: staging